export type CodeAction =
  | "refactor"
  | "fix-bugs"
  | "explain"
  | "database-schema"
  | "api-endpoints"
  | "documentation"
  | "security-audit"
  | "performance-audit";

export const CODE_ACTIONS: Record<
  CodeAction,
  {
    label: string;
    prompt: string;
  }
> = {
  "api-endpoints": {
    label: "Generate API Endpoints",
    prompt:
      "Generate or improve API route files, request/response contracts, validation, and endpoint documentation for this project.",
  },
  "database-schema": {
    label: "Generate Database Schema",
    prompt:
      "Generate or improve the database schema, migrations, table relationships, RLS or authorization notes, and seed examples.",
  },
  documentation: {
    label: "Generate Documentation",
    prompt:
      "Generate developer documentation, setup instructions, architecture notes, and usage examples for this project.",
  },
  explain: {
    label: "Explain Code",
    prompt:
      "Explain the architecture, key files, data flow, and implementation decisions in clear technical notes.",
  },
  "fix-bugs": {
    label: "Fix Bugs",
    prompt:
      "Identify likely bugs and produce corrected files or patch notes. Preserve the intended behavior.",
  },
  "performance-audit": {
    label: "Performance Audit",
    prompt:
      "Audit the project for performance risks and generate targeted improvements, including code or configuration changes.",
  },
  refactor: {
    label: "Refactor Code",
    prompt:
      "Refactor the project for maintainability, readability, and better separation of concerns without changing the product scope.",
  },
  "security-audit": {
    label: "Security Audit",
    prompt:
      "Audit the project for security risks and generate fixes or security notes around authentication, authorization, validation, secrets, and dependencies.",
  },
};

export const DEFAULT_CODE_FILES = [
  {
    file_name: "README.md",
    file_path: "README.md",
    content:
      "# Generated Project\n\nThis project was generated by ORIVOO Code Studio.\n\n## Next steps\n\n- Review files\n- Install dependencies\n- Run tests\n",
  },
];
