import JSZip from "jszip";
import { DEFAULT_CODE_FILES } from "@/lib/code/config";

export type GeneratedCodeFile = {
  content: string;
  file_name: string;
  file_path: string;
};

export type GeneratedCodeProject = {
  description: string;
  files: GeneratedCodeFile[];
  framework: string;
  language: string;
  title: string;
};

export function extractJsonObject(text: string) {
  const fencedMatch = text.match(/```(?:json)?\s*([\s\S]*?)```/i);
  const candidate = fencedMatch?.[1] ?? text;
  const start = candidate.indexOf("{");
  const end = candidate.lastIndexOf("}");

  if (start === -1 || end === -1 || end <= start) {
    throw new Error("AI response did not include structured JSON.");
  }

  return candidate.slice(start, end + 1);
}

export function parseGeneratedCodeProject(text: string): GeneratedCodeProject {
  const parsed = JSON.parse(extractJsonObject(text)) as Partial<GeneratedCodeProject>;

  if (!parsed.title || !parsed.description || !Array.isArray(parsed.files)) {
    throw new Error("AI response missed required code project fields.");
  }

  const files = parsed.files
    .map((file) => normalizeFile(file))
    .filter((file): file is GeneratedCodeFile => Boolean(file));

  return {
    description: parsed.description,
    files: files.length ? ensureBaseFiles(files, parsed.framework) : DEFAULT_CODE_FILES,
    framework: parsed.framework ?? "Not specified",
    language: parsed.language ?? "TypeScript",
    title: parsed.title,
  };
}

export function fileNameFromPath(filePath: string) {
  return filePath.split("/").filter(Boolean).at(-1) ?? filePath;
}

export function buildFolderTree(files: { file_path: string }[]) {
  return files
    .map((file) => file.file_path)
    .sort((a, b) => a.localeCompare(b))
    .join("\n");
}

export async function createCodeZip({
  exportType,
  files,
  projectTitle,
}: {
  exportType: "zip" | "next" | "react" | "node";
  files: GeneratedCodeFile[];
  projectTitle: string;
}) {
  const zip = new JSZip();
  const normalizedFiles = ensureExportFiles(files, exportType, projectTitle);

  for (const file of normalizedFiles) {
    zip.file(file.file_path, file.content);
  }

  return zip.generateAsync({ type: "uint8array" });
}

export function sanitizeDownloadName(name: string) {
  return name.replace(/[^a-zA-Z0-9-_]+/g, "-").replace(/-+/g, "-").slice(0, 80);
}

function normalizeFile(file: Partial<GeneratedCodeFile> | undefined) {
  if (!file?.file_path || typeof file.content !== "string") {
    return null;
  }

  const filePath = file.file_path.replace(/^\/+/, "");

  return {
    content: file.content,
    file_name: file.file_name || fileNameFromPath(filePath),
    file_path: filePath,
  };
}

function ensureBaseFiles(files: GeneratedCodeFile[], framework?: string) {
  const nextFiles = [...files];

  if (!nextFiles.some((file) => file.file_path === "README.md")) {
    nextFiles.unshift({
      content: `# Generated Code Project\n\nFramework: ${
        framework ?? "Not specified"
      }\n\nGenerated by ORIVOO Code Studio.\n`,
      file_name: "README.md",
      file_path: "README.md",
    });
  }

  return nextFiles;
}

function ensureExportFiles(
  files: GeneratedCodeFile[],
  exportType: "zip" | "next" | "react" | "node",
  projectTitle: string,
) {
  const nextFiles = ensureBaseFiles(files, exportType);

  if (exportType === "zip") {
    return nextFiles;
  }

  const hasPackageJson = nextFiles.some((file) => file.file_path === "package.json");

  if (!hasPackageJson) {
    const dependencies =
      exportType === "node"
        ? { "@types/node": "latest", typescript: "latest" }
        : exportType === "next"
          ? { next: "latest", react: "latest", "react-dom": "latest" }
          : { "@vitejs/plugin-react": "latest", vite: "latest", react: "latest", "react-dom": "latest" };

    nextFiles.unshift({
      content: JSON.stringify(
        {
          name: sanitizeDownloadName(projectTitle).toLowerCase() || "orivoo-code-project",
          private: true,
          scripts:
            exportType === "node"
              ? { build: "tsc", dev: "tsx src/index.ts", start: "node dist/index.js" }
              : exportType === "next"
                ? { build: "next build", dev: "next dev", start: "next start" }
                : { build: "vite build", dev: "vite", preview: "vite preview" },
          dependencies,
        },
        null,
        2,
      ),
      file_name: "package.json",
      file_path: "package.json",
    });
  }

  return nextFiles;
}
